"""
Minimal end-to-end example: generate a two-session synthetic subject with
theta-gamma PAC, save it to disk, and print a summary.

Run from the project root:
    python examples/quickstart.py
"""

import pac_framework as pac

# ── 1. Electrode layout ────────────────────────────────────────────────────────

channel_info = pac.channel_info_from_shafts([
    {"shaft": "LA", "region": "amygdala",    "contacts": 8, "spacing_mm": 1.5},
    {"shaft": "LH", "region": "hippocampus", "contacts": 8, "spacing_mm": 1.5},
])

# ── 2. Two sessions with the same event structure ─────────────────────────────

specs = [
    pac.SessionSpec(
        date=f"2026-01-0{i + 1}",
        duration_sec=60.0,
        task="memory_task",
        event_catalog=(
            pac.EventClass(name="cue_onset",    rate_hz=0.5, min_gap_sec=2.0),
            pac.EventClass(name="decision_made", rate_hz=0.4, min_gap_sec=1.5),
        ),
    )
    for i in range(2)
]

sessions = pac.build_sessions(
    subject_name="example_sub",
    seed=42,
    sfreq=1000.0,
    session_specs=specs,
    channel_info=channel_info,
)

# ── 3. Signal model ────────────────────────────────────────────────────────────
#
# Theta drives gamma amplitude (classic theta-gamma PAC).
# Coupling depth rises from 0.2 to 0.8 in the 1.5 s following each cue onset.

theta = pac.OscillatorPopulation(
    id="theta",
    center_frequency=6.0,
    bandwidth=2.0,
    amplitude=50.0,
    region="hippocampus",
    paf_drift=pac.PAFDrift(sigma_hz=0.3, tau_seconds=8.0),
)

gamma = pac.OscillatorPopulation(
    id="gamma",
    center_frequency=70.0,
    bandwidth=10.0,
    amplitude=10.0,
    region="hippocampus",
    burst=pac.BurstConfig(mode="bursty", rate_hz=1.5, duration_cycles_mean=4.0),
)

bg = pac.BackgroundPopulation(
    id="bg",
    slope=1.5,
    knee_hz=5.0,
    amplitude=8.0,
)

config = pac.SignalConfig(
    populations=[theta, gamma, bg],
    couplings=[
        pac.PhaseToAmpCoupling(
            driver="theta",
            target="gamma",
            chi=0.2,
            phi_0=0.0,
            kappa=3.0,
            event_modulations=(
                pac.EventModulation(
                    event_label="cue_onset",
                    peak_chi=0.8,
                    window_sec=1.5,
                    latency_sec=0.05,
                    edge_fraction=0.25,
                ),
            ),
        ),
    ],
    projection=pac.ProjectionConfig(mode="region_match", channel_noise_sd=3.0),
)

# ── 4. Synthesise ──────────────────────────────────────────────────────────────

sessions = pac.generate_signals(
    sessions=sessions,
    signal_configs=[config, config],
    master_seed=42,
    subject_name="example_sub",
)

# ── 5. Inspect ────────────────────────────────────────────────────────────────

for s in sessions:
    print(s.summary())
    chi = s.ground_truth["chi_trajectories"]["theta__to__gamma"]
    print(f"  chi range: {chi.min():.3f} – {chi.max():.3f}  (baseline 0.2, peak 0.8)")
    print()

# ── 6. Save ───────────────────────────────────────────────────────────────────

from pathlib import Path
from pac_framework.gui.persistence import save_subject
from pac_framework.gui.subject_state import SubjectState

state = SubjectState(
    subject_name="example_sub",
    master_seed=42,
    notes="Generated by examples/quickstart.py",
    sfreq=1000.0,
    sessions=sessions,
    channel_layout=[
        {"shaft": "LA", "region": "amygdala",    "contacts": 8, "spacing_mm": 1.5},
        {"shaft": "LH", "region": "hippocampus", "contacts": 8, "spacing_mm": 1.5},
    ],
    session_signal_configs=[config, config],
    signals_populated=True,
)

out_dir = Path(__file__).parent / "example_sub"
save_subject(state, out_dir, supplementary={"sessions": [], "channel_layout": [], "signal": {}})
print(f"Saved to {out_dir}")
